# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='massage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toperson', models.CharField(max_length=50)),
                ('textcontent', models.TextField(max_length=200)),
                ('filecontent', models.FileField(null=True, upload_to='./massagefile/')),
                ('imagecontent', models.ImageField(null=True, upload_to='./massageimage/')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('birth', models.DateField(default='sercert')),
                ('signdate', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('addressnow', models.TextField(default='unknown', max_length=150)),
                ('localplace', models.TextField(default='unknown', max_length=150)),
                ('motto', models.TextField(blank=True, max_length=500)),
                ('tofind', models.BooleanField(default='True')),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='./userimage/')),
                ('online', models.BooleanField(default='False')),
                ('friend', models.ManyToManyField(to='weibo_app1.person')),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubtime', models.DateTimeField(auto_now_add=True)),
                ('pubtext', models.TextField(max_length=200)),
                ('pubimage', models.ImageField(null=True, upload_to='./pubimage/')),
                ('viewpermission', models.CharField(choices=[('all', 'all'), ('friend', 'friend')], default='all', max_length=5)),
                ('pubperson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weibo_app1.person')),
            ],
        ),
        migrations.AddField(
            model_name='massage',
            name='fromperson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weibo_app1.person'),
        ),
    ]
