# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='account name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tofind',
            field=models.BooleanField(default='True', verbose_name='To be find by stranges or not.'),
        ),
    ]
