# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_app1', '0003_auto_20170312_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='_person_friend_+', to='weibo_app1.person'),
        ),
    ]
