# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_app1', '0003_auto_20170315_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='friend',
            field=models.ManyToManyField(blank=True, to='weibo_app1.person'),
        ),
    ]
