# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_app1', '0006_auto_20170319_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='fromperson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='massage_from', to='weibo_app1.person'),
        ),
        migrations.RemoveField(
            model_name='massage',
            name='toperson',
        ),
        migrations.AddField(
            model_name='massage',
            name='toperson',
            field=models.ManyToManyField(related_name='massage_to', to='weibo_app1.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/media//userimage/'),
        ),
    ]
