# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_app1', '0007_auto_20170320_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='filecontent',
            field=models.FileField(blank=True, null=True, upload_to='./massagefile/'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='fromperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massage_from', to='weibo_app1.person'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='imagecontent',
            field=models.ImageField(blank=True, null=True, upload_to='./massageimage/'),
        ),
    ]
