# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_app1', '0009_auto_20170320_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='pubimage',
            field=models.ImageField(blank=True, null=True, upload_to='/media//pubimage/'),
        ),
        migrations.AlterField(
            model_name='status',
            name='pubperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo_app1.person'),
        ),
        migrations.AlterField(
            model_name='status',
            name='pubtext',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
