# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_app1', '0010_auto_20170320_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='viewpermission',
            field=models.CharField(choices=[('all', 'all'), ('friend', 'friend')], default='all', max_length=8),
        ),
    ]
