# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_app1', '0011_auto_20170320_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='account name'),
        ),
    ]
